#!/bin/sh

# Takes a snapshot of '/' into '/snapshots/system/<date>_<number>_<comment>'
snap(){
	local date=$(date +%Y-%m-%d)
	local number=$(( $(ls /snapshots/system | cut -d '_' -f 2 | sort -n | tail -n 1) + 1 ))
	printf "Enter the snapshot's comment: "
	read
	local comment=$REPLY

	btrfs subvolume snapshot -r / /snapshots/system/${date}_${number}_${comment}
}